Pytest extensions (#3338)
* chore: initial switch to pytest

* chore: configure pytest in pyproject

* chore: quick pre-commit fix

* chore: first try on the action for pytest

* chore: fixes for pytest in the pipeline

* chore: fixes for pytest in the pipeline

* chore: fixes for pytest in the pipeline

* chore: started on article tests

* chore: added run configs

* chore: added run configs

* chore: added coverage support

* chore: conflict fixes

* chore: extending tests

* chore: more tests

* chore: publish test reports

* chore: test get article by news site

* chore: test get article by multiple news sites

* chore: test get article by multiple news sites

* chore: started on article tests

* chore: test ordering

* chore: cleanup

* chore: call linters separately

* chore: stick to ubuntu for now

* chore: stick to ubuntu for now

* chore: stick to ubuntu for now

* chore: run on python 3.12

* chore: bandit config

* chore: bandit config

* chore: added ruff

* chore: added ruff

* chore: test greater_then filter

* chore: test update_at filter

* chore: test lower_then

* chore: test search

* chore: test search

* chore: test search on summary

* chore: fix path issue

* chore: test title_contains filters

* chore: test summary_contains filters

* chore: implemented events related tests

* chore: fix path not exists

* chore: id can just be the index

* chore: started work on reports

* chore: demo env variables

* chore: tests for the reports endpoint

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -1,14 +1,39 @@
-name: Testing and Linting
+name: Lining and Testing
 on:
   pull_request:
 
 jobs:
-  pre-commit:
+  linters:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
-      - uses: actions/setup-python@v3
-      - uses: pre-commit/action@v3.0.0
+        - name: Check out the repo
+          uses: actions/checkout@v3
+
+        - uses: actions/setup-python@v4
+          with:
+            python-version: '3.12'
+
+        - name: Install dependencies
+          run: |
+            python -m pip install --upgrade pip
+            pip install poetry
+            poetry export -f requirements.txt --output requirements.txt --without-hashes --with=dev
+            pip install -r requirements.txt
+
+        - name: Run linters
+          run: |
+            mkdir test_results
+            black --check .
+            isort --check-only --diff .
+            bandit -c pyproject.toml -r . -f xml -o test_results/TEST-bandit.xml
+            ruff check .
+
+        - name: Publish linter reports
+          uses: mikepenz/action-junit-report@v4
+          if: success() || failure() # always run even if the previous step fails
+          with:
+            report_paths: 'test_results/TEST-*.xml'
+
 
   tests:
     runs-on: ubuntu-latest
@@ -17,7 +42,7 @@ jobs:
         uses: actions/checkout@v3
 
       - name: Set up Python
-        uses: actions/setup-python@v3
+        uses: actions/setup-python@v4
         with:
           python-version: "3.12"
 
@@ -29,4 +54,10 @@ jobs:
           pip install -r requirements.txt
 
       - name: Run tests
-        run: pytest
+        run: pytest --junitxml=test_results/TEST-pytest.xml
+
+      - name: Publish test report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: 'test_results/TEST-*.xml'
